// Auto-generated by deploy.js — DO NOT EDIT
// Deployed: 2026-03-13T15:53:47.502Z
// Network:  sepolia (chainId: 11155111)

export const CONTRACT_ADDRESSES = {
  LAND_REGISTRY:     '0x1B19F7A7D5c4019bC0a856b562FBF820Ab4CDb6A',
  TRANSFER_CONTRACT: '0xbBC928458C8220F4b976cF0b5E8c3BEBa51d25Ca',
};

export const NETWORK_CONFIG = {
  chainId:     11155111,
  name:        'sepolia',
  explorer:    'https://sepolia.etherscan.io',
  rpcUrl:      'https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY',
};

export const EXPLORER_URL = 'https://sepolia.etherscan.io';
